### ISSUE TITLE
gui not starting after install with conda on win64

### ISSUE THREAD

**Issue by christian34** [openalea/visualea#1]
Hi, 

I just test the visualea conda intall on my win64 (conda install -c openalea openalea.visualea).
When I tried runing visualea, nothing append. 

I investigate a little bit more launching from ipython using: 

from openalea.visualea.visualea_script import start_gui
start_gui()

I got a first error asking for openalea.oalab (for the interpreter). Is this dependency expected ?
After (conda) install of  oalab, I got a second message for importing openalea.misc (same question ?)
After installng openalea.misc, I got the following error 

![image](https://user-images.githubusercontent.com/4168869/36140140-7862a7d8-10a0-11e8-971b-cf3c47bf19a8.png)

That's all folks !

**Comment by pradal** [comment]
Thanks a lot for the test!!!
No, this is not expected.

**Comment by artzet-s** [comment]
![carbon](https://user-images.githubusercontent.com/2472052/36141798-6b423748-10a6-11e8-9d78-cef65fa71bba.png)

**Comment by pradal** [comment]
Can you test again in a new environment?
I have fixed the issue with #2 
Just create a new environment like

conda create -n visualea -c openalea openalea.visualea
activate visualea
visualea

**Comment by christian34** [comment]
Geat job !! It works perfectly !! Thanks !

**Comment by pradal** [comment]
A long wait, but we succeed. The future is bright ;)
