### ISSUE TITLE
Visualea's logger Python2 / QT4 to Python3 / QT5 

### ISSUE THREAD

**Issue by baugetfa** [openalea/visualea#19]
logger absent with Qt5

**Comment by baugetfa** [comment]
fixed in `openalea.core` with commit [37dcd80](https://github.com/openalea/core/commit/37dcd80d53c3fb1b7bf3e8587e1ea7b4d16742e1)

**Comment by pradal** [comment]
Great.
But can you improve the code to take into account the diversity of backends?

**Comment by baugetfa** [comment]
in commit [37dcd80](https://github.com/openalea/core/commit/37dcd80d53c3fb1b7bf3e8587e1ea7b4d16742e1)

**Comment by baugetfa** [comment]
done and the diversity of backends is taken into account with qtpy
