### ISSUE TITLE
Missing python base function in visualea like getitem

### ISSUE THREAD

**Issue by artzet-s** [openalea/visualea#9]
![1](https://user-images.githubusercontent.com/2472052/38937655-f80a0b1a-4323-11e8-9dcb-5ffd8f0bbbbc.png)

![2](https://user-images.githubusercontent.com/2472052/38937656-f8b18020-4323-11e8-81ab-f130624e5ab1.png)

Tested with win64 conda installation : 

> conda create -n visualea python
> activate visualea
> conda install -c openalea openalea.visualea  pyqt=4.10.4 qtconsole
> visualea

And with "git clone" + "python setup.py install" on openalea repository : core, vpltk, grapheditor, misc, oalab, visualea

**Comment by pradal** [comment]
Sure. These components are in openalea.components.
I have to make a meta package that contains all this stuff.

**Comment by artzet-s** [comment]
Thanks, @pradal I fix my problem with : 

> git clone https://github.com/openalea/openalea-components
> cd openalea-components
> python multisetup.py install
> visualea

![1](https://user-images.githubusercontent.com/2472052/38939571-80f5d11c-4328-11e8-8b8c-83d3a95ec65b.png)
![2](https://user-images.githubusercontent.com/2472052/38939573-82cff6ca-4328-11e8-8d61-da109c5d9629.png)

**Comment by pradal** [comment]
Just do 👍 conda install -c openalea openalea.components

**Comment by artzet-s** [comment]
Thanks again, I close the issue, is not a bug.
